# Generated by Django 6.0.5 on 2026-05-09 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('BRANCA', 'Branca'), ('CINZA', 'Cinza'), ('AMARELA', 'Amarela'), ('LARANJA', 'Laranja'), ('VERDE', 'Verde'), ('AZUL', 'Azul'), ('ROXA', 'Roxa'), ('MARROM', 'Marrom'), ('PRETA', 'Preta')], max_length=30)),
                ('graus', models.PositiveIntegerField(default=0)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduacoes', to='academias.academia')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos/')),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tempo_graduacao', models.CharField(blank=True, max_length=100, null=True)),
                ('vencimento', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('TRANCADO', 'Trancado')], default='ATIVO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='academias.academia')),
                ('graduacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='alunos.graduacao')),
            ],
        ),
    ]
