# Generated by Django 6.0.5 on 2026-05-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_aluno_altura'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
