# Generated by Django 6.0.5 on 2026-05-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_aluno_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='vencimento',
        ),
    ]
