# Generated by Django 6.0.5 on 2026-05-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0001_initial'),
        ('alunos', '0004_remove_aluno_vencimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='graduacao',
            options={'ordering': ['ordem']},
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['academia'], name='alunos_alun_academi_88854f_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['status'], name='alunos_alun_status_a5494c_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['graduacao'], name='alunos_alun_graduac_8f3807_idx'),
        ),
    ]
