# Generated by Django 6.0.5 on 2026-05-16 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0001_initial'),
        ('alunos', '0005_alter_aluno_options_alter_graduacao_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graduacao',
            unique_together={('academia', 'nome')},
        ),
    ]
