# Generated by Django 6.0.5 on 2026-05-11 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0001_initial'),
        ('alunos', '0003_aluno_qr_code'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensalidade',
            old_name='criada_em',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='mensalidade',
            old_name='vencimento',
            new_name='vencimento',
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='valor_pago',
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='academia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academias.academia'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=20),
        ),
    ]
