# Generated by Django 6.0.5 on 2026-05-09 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0001_initial'),
        ('alunos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('JIU_JITSU', 'Jiu-Jitsu'), ('NO_GI', 'No-Gi'), ('INFANTIL', 'Infantil'), ('FEMININO', 'Feminino')], max_length=30)),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='academias.academia')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_presenca', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='alunos.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='aulas.aula')),
            ],
            options={
                'unique_together': {('aula', 'aluno')},
            },
        ),
    ]
